### ISSUE TITLE
terminator and -w / strange workspace switch behaviour

### ISSUE THREAD

**Issue by benzkji** [mkropat/jumpapp#26]
If I `jumapp -w terminator`, and no terminator window is open on my current workspace, I'll get the new terminator, but get switched to a workspace with an existing terminator window. Very strange behaviour, I have not experienced this with any other application. Any way I could debug this, or get more info? Also, am I the only one with this specific problem?

    jumpapp -w -L terminator

shows no matching windows. also, when a terminator window exists, everything operates normally.

I'm on XFCE / xubuntu (zesty)

**Comment by mkropat** [comment]
Strange behavior. Thanks for posting the `-L` output, that helps a lot.

Since no matching windows are found, my assumption is that jumpapp is running [this code](https://github.com/mkropat/jumpapp/blob/master/jumpapp#L85) and wmctrl isn't called at all (which is how jumpapp focuses windows). This makes me think the weird workspace switching behavior is coming from the program being launched (that is, terminator).

What happens in the same circumstances if instead of running `jumapp -w terminator` you simply run `terminator` (without jumpapp)?

Also, another thing to try is to run `jumapp -w -n terminator` (no forking) and see if that makes any difference.

**Comment by benzkji** [comment]
It says (can I get more info/output?)
    
    Matched Windows [0]

Now, another thing: Switching to an empty workspace. Hitting the terminator shortcut (or entering `terminator` in xfce4-terminal, does the same). Closing the terminator window and re-hitting the shortcut does thenafter behave normal! When closing all terminator windows, switching workspace, switching back, the procedure again begins...

I guess (as you also said) this is an issue with terminator (handling things when existing windows found?), not jumpapp.

**Comment by mkropat** [comment]
Cool. The jumpapp output is just saying that there were 0 matched windows given the arguments. That's all the debug info that jumpapp will give you currently.

jumpapp will probably never be able to give too much diagnostic info, since it's written at such a high level (all the heavy lifting is done by wmctrl). But there might be other tools out there that would help that I'm not familiar with. I'm thinking stuff like [xprop](http://www.xfree86.org/4.0/xprop.1.html) but programs that do even more.
