### ISSUE TITLE
Can't switch to Slack

### ISSUE THREAD

**Issue by raxod502** [mkropat/jumpapp#42]
Running `wmctrl -a slack` works as desired, but `jumpapp slack` reports `Error: found running process for 'slack', but found no window to jump to`. This is curious since `wmctrl -lp` gives `0x04400005  0 1277   shallan Slack - CS 121` and `ps -q 1277` gives ` 1277 ?        00:00:25 slack`.

On the other hand, `jumpapp (firefox|emacs|skype|konsole)` works as expected.

Manjaro Linux latest as of 2019-05-06 with `jumpapp-git` r93.dba1062-1 from AUR, wmctrl 1.07-5 from official repositories.

**Comment by 3nuc** [comment]
Having the same issue.

Temporary workaround: `wmctrl -a "slack" -v || slack` - bind this to a shortcut in your WM instead of jumpapp.

**Comment by raxod502** [comment]
I use `focus-or-launch slack`, with the following script:

```bash
#!/usr/bin/env bash

set -e
set -o pipefail

app="$1"

out="$(wmctrl -lp | awk '{print $1, $3}')"
while read -r window pid; do
    procname="$(ps -q "$pid" -o comm)"
    if [[ "$procname" == *"$app"* ]]; then
        echo "Focusing $app." 1>&2
        wmctrl -i -a "$window"
        exit 0
    fi
done <<< "$out"

if [[ -f "/usr/share/applications/${app}.desktop" ]]; then
    echo "Launching $app." 1>&2
    gtk-launch "$app"
    exit 0
fi

out="$(ls /usr/share/applications)"
while read -r desktop; do
    if [[ "$desktop" == *"$app".desktop ]]; then
        desktop="${desktop##*/}"
        desktop="${desktop%%.desktop}"
        echo "Launching $desktop." 1>&2
        gtk-launch "$desktop"
        exit 0
    fi
done <<< "$out"

echo "Couldn't find $app in /usr/share/applications." 1>&2
exit 1
```

Unfortunately, it doesn't work when Slack is minimized into the system tray.

**Comment by mkropat** [comment]
Thanks for the report! I'm trying to catch up on everything I missed the past couple months while I moved cities and jobs.

The reason jumpapp can't find Slack is because jumpapp is [filtering based on the window type](https://github.com/mkropat/jumpapp/blob/e50ffa5/jumpapp#L124). IIRC the reason we do this is to filter out weird helper windows and popups and such when switching windows.

jumpapp looks up the window type by querying the `_NET_WM_WINDOW_TYPE` property of the window. This works great as long as the window returns [a standard window type](https://standards.freedesktop.org/wm-spec/wm-spec-latest.html#idm140200472629520). Unfortunately, the Slack app does not conform to the standard:

```sh
$ xprop | grep TYPE
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_MAIN
```

It appears this is not the first project [to have to deal with the non-conforming Slack implementation](https://forum.manjaro.org/t/slack-not-showing-when-tabbing-between-apps/86759).

I see a a few options:

1. Add a new option to disable filtering on the window type
1. Hardcode support for the `_NET_WM_WINDOW_TYPE_MAIN` type
1. Reverse the window type match, so that it filters out `_NET_WM_WINDOW_TYPE_DESKTOP`, `_NET_WM_WINDOW_TYPE_DOCK`, etc., so that whatever is left (such as `_NET_WM_WINDOW_TYPE_NORMAL` or unrecognized values like `_NET_WM_WINDOW_TYPE_MAIN`) is allowed

Since there haven't been many (any?) bug reports up till now involving applications with misbehaving window types, I'm hesitant to add yet another option to jumpapp in order to handle this special case. That is why I am leaning towards either option 2 or 3.

Does anyone have any thoughts?

**Comment by raxod502** [comment]
Thanks for excellent report! It seems to me like option 3 would be the best.

**Comment by lucian303** [comment]
This sort of works for me. I can run `jumpapp -p slack` and it works from the terminal, but if I assign that exact command to a keyboard shortcut (KDE / Kubuntu 18.04), it doesn't work. `wmctrl -a "Slack - UCF"` also works ("Slack - UCF") is the name of my slack window. Any ideas?

**Comment by mkropat** [comment]
I implemented option 3 here: https://github.com/mkropat/jumpapp/pull/43

It works for Slack on my machine, but I wouldn't mind a second set of eyes. Does someone want to try it out and see if it works for them? If it looks good, I'll merge it.

**Comment by 3nuc** [comment]
Hey I tried it out and `jumpapp slack` works for me after I replaced the old version in my /usr/bin. I also bound `jumpapp slack` to a shortcut to verify if I won't get the same problem as lucian303 above, but everything works fine :)

I started using ALT+TAB because of Slack, gotta relearn how to use the computer like a normal person.

**Comment by mkropat** [comment]
The fix for this is [now released](https://github.com/mkropat/jumpapp/releases/tag/v1.1). Feel free to open a new issue if you run into any problems with other applications on the new version.
