### ISSUE TITLE
Error when using jumpapp in dwm

### ISSUE THREAD

**Issue by MaxGyver83** [mkropat/jumpapp#54]
`jumpapp` works perfectly for me in GNOME. Now I'm playing around with [dwm](https://dwm.suckless.org/). Here, I can start a program with jumpapp (for example with `jumpapp firefox`). But when Firefox is already running, I get:

```bash
~ ▶ jumpapp firefox
/usr/bin/jumpapp: Zeile 248: [[: window.: Syntaxfehler: Ungültiger arithmetischer Operator. (Fehlerverursachendes Zeichen ist ».«).
```
This translates roughly to:

```
Line 248: [[: window.: syntax error: Invalid arithmetic operator. (error token is ».«).
```
Any idea what this means?

**Comment by mkropat** [comment]
Confirmed bug on dwm. Interesting. I'm not sure why this is happening. If I find time I will try to diagnose further.

**Comment by mkropat** [comment]
The issue is that jumpapp relies on `_NET_CLIENT_LIST_STACKING`:

https://github.com/mkropat/jumpapp/blob/944723f50c21a5771c59a2ae8e091704c1bc57c1/jumpapp#L381

However, dwm does not support that window property. Which kind of makes sense, since dwm is a tiling window manager (as opposed to a *stacking* window manager).

dwm does support `_NET_CLIENT_LIST`, which maybe jumpapp could use as a fallback?

One complication I noticed is that `xprop(1)` appears to return a success status (`0`) even when the window property requested does not exist. This could make detecting missing support for `_NET_CLIENT_LIST_STACKING` annoying. Still, I'm sure there's a way it could be done (while hopefully preserving broad *nix support).

I don't think I have time to code a fix myself, but PRs are most welcome (please make sure to add appropriate [unit test coverage](https://github.com/mkropat/jumpapp/blob/master/t/test_jumpapp)).

**Comment by MaxGyver83** [comment]
Thanks for your investigation. Good to know that it's only a problem in dwm. My workaround is to directly use wmctrl. For example I have bound `Win+f` to: `pgrep -f firefox &> /dev/null && wmctrl -a firefox || firefox`. That's ok as I usually just have one Firefox window opened. Same for my terminal (Alacritty + byobu). Currently I'm checking out [awesome](https://awesomewm.org/) which seems to be EWMH compliant (which means that it supports `_NET_CLIENT_LIST_STACKING`!?).
