### ISSUE TITLE
Using with flatpak apps

### ISSUE THREAD

**Issue by ceranco** [mkropat/jumpapp#55]
Hello, I'm greatly enjoying using jumpapp, but I've recently hit a snag.

I've installed MellowPlayer using flatpak, and when I run `jumpapp MelloPlayer` when it's running it fails with the following error:
> Error: found running process for 'MellowPlayer', but found no window to jump to

I'm not sure what's happening, as the window is open:
![Screenshot from 2020-10-06 11-29-32](https://user-images.githubusercontent.com/22302978/95177783-4906c980-07c7-11eb-8b7b-5688bcc8b8d3.png)

Thanks in advance!

**Comment by Lupccs** [comment]
Try to launch it with the -f option
jumpapp -f MellowPlayer


Il mar 6 ott 2020, 10:31 Eran Cohen <notifications@github.com> ha scritto:

**Comment by ceranco** [comment]
Hi @Lupccs, thanks for the quick response!

Running `jumpapp -f MellowPlayer` fails with the following message:
> Error: unable to find command 'MellowPlayer'

I think it might be because the only way to start flatpak apps is to run `flatpak run <APP_ID>`, so `MellowPlayer` doesn't exist in the `PATH`.

Either way, turns out that simply running `flatpak run MelloPlayer` will start a new instance, or focus the existing window if it already exists, so that's good enough for me.

Thanks again!

**Comment by miltsghostrehab** [comment]
I think that support for Flatpak apps would be useful -- though perhaps problematic to implement because of how they're launched.

If anyone came here looking for a fix or a workaround (as I did), try this:
1. Create a file somewhere in your `<PATH>` named after the program you want to launch (no extension).
2. Make the file executable (`chmod +x <FILE_NAME>`)
3. Add this bit of code to the file:
```bash
nohup flatpak run <APP_ID> </dev/null >/dev/null 2>&1 &
```
Breakdown of what this code does:
| code | description |
|---|---|
| `nohup` | [nohup is a POSIX command to ignore the HUP signal](https://en.wikipedia.org/wiki/nohup) |
| `flatpak run` | command used to launch any Flatpak command from terminal |
| `<APP_ID>` | the application ID which can be retrieved by running `flatpak list`; the ID will have (at least) three phrases separated by two periods, like `com.spotify.Client` or `com.gitlab.ColinDuquesnoy.MellowPlayer` |
| `</dev/null >/dev/null` | redirecting input and output to the null file so it doesn't get written to `nohup.out` (which is nohup's default behavior) |
| `2>&1` | [2>&1 redirects the standard error to the standard output so they appear together and can be jointly redirected to a file. (Writing just 2>1 would redirect the standard error to a file called "1", not to standard output.)](https://unix.stackexchange.com/a/89416) |
| The final `&` | launches the application in the background, detached from the terminal |
